# Usa una imagen oficial de Python
FROM python:3.9-slim

# Establece el directorio de trabajo en /app
WORKDIR /app

# Copia el archivo de aplicación al contenedor
COPY Python/Hola_Mundo.py /app

# Comando que se ejecutará cuando inicies el contenedor
CMD ["python", "Hola_Mundo.py"]


